language: python
dist: trusty

python:
    - "3.5"

install:
    pip install pyqt5 pygments mistune

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - cd ${TRAVIS_BUILD_DIR} && python -m unittest
